backend:
  name: git-gateway
  branch: production

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/code-of-conduct.md"
        label: "Code of Conduct"
        name: "coc"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "coc-page",
            }
          - {
              label: SEO Title,
              name: seoTitle,
              widget: string,
              required: false,
            }
          - {
              label: SEO Description,
              name: seoDescription,
              widget: string,
              required: false,
            }
      - file: "src/pages/resources.md"
        label: "Resources"
        name: "resources"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "resources-page",
            }
          - {
              label: SEO Title,
              name: seoTitle,
              widget: string,
              required: false,
            }
          - {
              label: SEO Description,
              name: seoDescription,
              widget: string,
              required: false,
            }
          - { label: Heading, name: resourcesHeader, widget: string, required: false }
          - {
              label: Subheader,
              name: resourcesSubheader,
              widget: markdown,
              required: false,
            }
          - label: Resources
            name: resourceList
            widget: list
            fields:
              - { label: Order, name: id, widget: number, required: false }
              - { label: Category, name: category, widget: string, required: false }
              - { label: Links, name: content, widget: markdown, required: false }
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: SEO Title,
              name: seoTitle,
              widget: string,
              required: false,
            }
          - {
              label: SEO Description,
              name: seoDescription,
              widget: string,
              required: false,
            }
          - { label: Heading, name: header, widget: string, required: false }
          - {
              label: Subheader,
              name: subheader,
              widget: markdown,
              required: false,
            }
          - { label: About Heading, name: aboutHeader, widget: string, required: false }
          - {
              label: About Section,
              name: aboutContent,
              widget: markdown,
              required: false,
            }   
          - label: Programming
            name: programmingList
            widget: list
            fields:
              - { label: Order, name: id, widget: number, required: false }
              - { label: Featured, name: featured, widget: boolean, required: false }
              - { label: Show Title, name: title, widget: string, required: false }
              - { label: Show Description, name: description, widget: markdown, required: false }
              - { label: Show Date, name: date, widget: string, required: false }
              - { label: Show Time, name: time, widget: string, required: false }

